# Generated by Django 3.0.7 on 2021-02-12 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0005_auto_20210129_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='similarEvents',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='events.Events_model')),
                ('similar_events', models.CharField(max_length=200)),
            ],
        ),
    ]
