# Generated by Django 3.0.7 on 2021-03-05 08:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryRecommendedEvents',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rec_events', models.CharField(max_length=300)),
                ('latest_update', models.DateField(default=datetime.date(2021, 3, 5))),
            ],
        ),
    ]
