# Generated by Django 3.0.7 on 2021-03-05 08:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_auto_20210305_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyrecommendedevents',
            name='latest_update',
            field=models.DateField(default=datetime.datetime(2021, 3, 5, 8, 16, 38, 934522, tzinfo=utc)),
        ),
    ]
