# Generated by Django 3.0.7 on 2021-01-23 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=200)),
                ('e_description', models.TextField()),
                ('e_guest', models.CharField(max_length=100)),
                ('e_location', models.CharField(max_length=100)),
                ('e_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Event_keywords_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_keyword', models.CharField(max_length=50)),
                ('e_score', models.FloatField()),
                ('e_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Events_model')),
            ],
        ),
    ]
