# Generated by Django 3.0.7 on 2021-01-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events_model',
            name='e_guest',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='events_model',
            name='e_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='events_model',
            name='e_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
