# Generated by Django 3.0.7 on 2021-01-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210123_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events_model',
            name='e_guest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events_model',
            name='e_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
