# Generated by Django 3.0.7 on 2021-03-03 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210129_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_keywords_model',
            name='e_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_keywords', to='events.Events_model'),
        ),
    ]
