# Generated by Django 3.0.7 on 2021-03-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20210303_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_model',
            name='e_regis_count',
            field=models.IntegerField(default=0),
        ),
    ]
