# Generated by Django 3.0.7 on 2021-02-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_event_log',
            name='viewDetails',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_event_log',
            name='viewEvenDetails',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_event_log',
            name='viewMoreDetails',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_event_log',
            name='viewRegistration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
