# Generated by Django 3.0.7 on 2021-02-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20210207_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_event_log',
            name='viewEvenDetails',
        ),
        migrations.RemoveField(
            model_name='user_event_log',
            name='viewMoreDetails',
        ),
        migrations.AddField(
            model_name='user_event_log',
            name='viewDate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_event_log',
            name='viewLocation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_event_log',
            name='viewDetails',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_event_log',
            name='viewRegistration',
            field=models.IntegerField(default=0),
        ),
    ]
