# Generated by Django 3.0.7 on 2021-02-09 04:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_auto_20210129_1024'),
        ('collector', '0004_something'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='something',
            new_name='Event_User_log',
        ),
        migrations.DeleteModel(
            name='User_Event_log',
        ),
    ]
