# Generated by Django 3.0.7 on 2021-02-09 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_auto_20210209_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_user_log',
            name='timedetails',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
