# Generated by Django 3.0.7 on 2021-03-18 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_auto_20210317_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_user_log',
            name='timedetails',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 11, 47, 40, 686901)),
        ),
    ]
