# Generated by Django 3.0.7 on 2021-03-28 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_auto_20210328_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_user_log',
            name='timedetails',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 5, 12, 39, 612515)),
        ),
    ]
