# Generated by Django 3.0.7 on 2021-05-26 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0016_auto_20210526_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_user_log',
            name='timedetails',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 9, 23, 40, 75309)),
        ),
    ]
