# Generated by Django 3.0.7 on 2021-05-26 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0020_auto_20210526_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_user_log',
            name='timedetails',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 10, 25, 35, 454650)),
        ),
    ]
