# Generated by Django 3.0.7 on 2021-05-26 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_auto_20210328_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearch',
            name='time_details',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 9, 20, 13, 75909)),
        ),
    ]
